export const INDIAN_STATES = [
  { code: '01', stateCode: 'JK', name: 'Jammu and Kashmir' },
  { code: '02', stateCode: 'HP', name: 'Himachal Pradesh' },
  { code: '03', stateCode: 'PB', name: 'Punjab' },
  { code: '04', stateCode: 'CH', name: 'Chandigarh' },
  { code: '05', stateCode: 'UT', name: 'Uttarakhand' },
  { code: '06', stateCode: 'HR', name: 'Haryana' },
  { code: '07', stateCode: 'DL', name: 'Delhi' },
  { code: '08', stateCode: 'RJ', name: 'Rajasthan' },
  { code: '09', stateCode: 'UP', name: 'Uttar Pradesh' },
  { code: '10', stateCode: 'BR', name: 'Bihar' },
  { code: '11', stateCode: 'SK', name: 'Sikkim' },
  { code: '12', stateCode: 'AR', name: 'Arunachal Pradesh' },
  { code: '13', stateCode: 'NL', name: 'Nagaland' },
  { code: '14', stateCode: 'MN', name: 'Manipur' },
  { code: '15', stateCode: 'MZ', name: 'Mizoram' },
  { code: '16', stateCode: 'TR', name: 'Tripura' },
  { code: '17', stateCode: 'ML', name: 'Meghalaya' },
  { code: '18', stateCode: 'AS', name: 'Assam' },
  { code: '19', stateCode: 'WB', name: 'West Bengal' },
  { code: '20', stateCode: 'JH', name: 'Jharkhand' },
  { code: '21', stateCode: 'OR', name: 'Odisha' },
  { code: '22', stateCode: 'CT', name: 'Chhattisgarh' },
  { code: '23', stateCode: 'MP', name: 'Madhya Pradesh' },
  { code: '24', stateCode: 'GJ', name: 'Gujarat' },
  { code: '25', stateCode: 'DD', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: '27', stateCode: 'MH', name: 'Maharashtra' },
  { code: '28', stateCode: 'AP', name: 'Andhra Pradesh' },
  { code: '29', stateCode: 'KA', name: 'Karnataka' },
  { code: '30', stateCode: 'GA', name: 'Goa' },
  { code: '31', stateCode: 'LD', name: 'Lakshadweep' },
  { code: '32', stateCode: 'KL', name: 'Kerala' },
  { code: '33', stateCode: 'TN', name: 'Tamil Nadu' },
  { code: '34', stateCode: 'PY', name: 'Puducherry' },
  { code: '35', stateCode: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: '36', stateCode: 'TG', name: 'Telangana' },
  { code: '37', stateCode: 'LA', name: 'Ladakh' },
  { code: '38', stateCode: 'OT', name: 'Other Territory' },
];

export const CLIENT_TYPES = {
  BUSINESS: 'BUSINESS',
  INDIVIDUAL: 'INDIVIDUAL',
};

export const CLIENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};
